### ISSUE TITLE
Implement class / struct cluster for a Musical Metronome

### ISSUE THREAD

**Issue by jsbean** [jsbean/HansTools#18]
Currently, `metronome` is just a single-level construction where the `ViewController` is controlling its:
- musical logic (sometimes beats are in eighth-notes, sometimes quarters, etc.).
- timing logic
- drawing logic

We need to encapsulate each of these responsibilities into their own, modular universes.

This will enable this (very reusable) construction to be reused for many pieces.

Implement:

``` Swift
struct Tempo // understands metrical durations to a degree -- use dn-m/Duration
class MetronomeViewController // sends messages to MetronomeView to engage
class MetronomeView: UIView // only knows about drawing, perhaps how long its blink is.
```

**Comment by jsbean** [comment]
In the long term, we will also want to avoid `NSTimer`, as this a very [inaccurate timing mechanism](http://atastypixel.com/blog/experiments-with-precise-timing-in-ios/) (especially when you consider the resolution of timing in musical settings).

**Comment by jsbean** [comment]
I will implement this [here](https://github.com/dn-m/MetronomeController) in the framework of a framework that we can integrate later into your project.

**Comment by hanstutschku** [comment]
Hi James,

I’m now getting back to coding.
First thing I pulled in case you changed something. But apparently I had not
pushed my very last version. Thus I got an error:

error: Your local changes to the following files would be overwritten by merge:
	SwiftAudioKitTest/ViewController.swift
Please, commit your changes or stash them before you can merge.




I therefore tried to push, which generated this error:

 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/jsbean/HansTools'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.



So I guess I will just continue local for the time being.

Bes,t Hans

**Comment by hanstutschku** [comment]
Hi James,

Thanks for all those suggestions.
I know that some of the current code in ViewController needs to be outsourced to other
classes. For now I’m just trying to replicate the functionality of my app for the voice piece
and I’m learning a lot while doing so.
Your input over the past days has been a great source and a push I probably needed to
start from a clean slate. I guess the beer(s) are on me!

Thanks, Hans

**Comment by jsbean** [comment]
Run:

```Bash
git commit -am "Store changes to appease git" # adds -A, then commits
git pull origin master # then, a weird thing should show up in the terminal
```
Type `:` then `x`. This should commit the merge locally.

**Comment by jsbean** [comment]
If that doesn't work, gimme a call.

**Comment by jsbean** [comment]
Closing this, as the most pertinent things have been dealt with by `dn-m/Timeline`, and a little bit with `dn-m/Timeline`.
